import type { Metadata } from "next";
import { fontSans } from "@/config/fonts";
import "@/styles/globals.css";
import { Header } from "@/sections/Header";
import { Footer } from "@/sections/Footer";
import { Testimonials } from "@/sections/Testimonials";
import { CallToAction } from "@/sections/CallToAction";

export const metadata: Metadata = {
  title: "Darkchain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.variable} suppressHydrationWarning>
        <Header />
        {children}
        <Testimonials />
        <CallToAction />
        <Footer />
      </body>
    </html>
  );
}
