import type { Metadata } from "next";
import { fontSans } from "@/config/fonts";
import "@/styles/globals.css";
import { Header } from "@/sections/Header";

export const metadata: Metadata = {
  title: "Darkchain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
